# Generated by Django 3.2.9 on 2021-11-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name01', models.CharField(max_length=250)),
                ('img01', models.ImageField(upload_to='pic01')),
                ('desc01', models.TextField()),
            ],
        ),
    ]
